language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.1
matrix:
  fast_finish: true
before_install:
# FIXME: I have no idea how and why six==1.11.0 i being installed
- pip uninstall -y six
- pip install -U setuptools
install:
- sed -ie "s#test-4.3#test-$PLONE_VERSION#" buildout.cfg
- python bootstrap.py
- bin/buildout annotate
- bin/buildout
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage --output-dir=htmlcov
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#simplesconsultoria
